ORG 0000H

START:
    MOV TMOD, #01H
    SETB TR0

ESPERA_USUARIO:
    MOV A, P2
    CJNE A, #0FFH, CONTINUA
    SJMP ESPERA_USUARIO

CONTINUA:
    MOV DPTR, #SEQUENCIA
    MOV R0, #0

MOSTRA_SEQUENCIA:
    MOV A, TL0
    ANL A, #07H
    CJNE A, #05H, OK
    MOV A, #00H
OK:
    CJNE A, #06H, OK2
    MOV A, #01H
OK2:
    CJNE A, #07H, MOSTRA_LED
    MOV A, #02H

MOSTRA_LED:
    MOV R5, A
    MOV A, R5
    MOVC A, @A+DPTR
    MOV P1, A
    ACALL DELAY

    INC R0
    CJNE R0, #5, MOSTRA_SEQUENCIA

    MOV P1, #0FFH
    MOV P2, #0FFH

MAIN:
    ACALL LER_TECLA
    CJNE A, #0FFH, ACENDE_LED
    SJMP MAIN

ACENDE_LED:
    CPL A
    MOV P1, A
    ACALL DELAY
    SJMP MAIN

LER_TECLA:
ESPERA_SOLTAR:
    MOV A, P2
    CJNE A, #0FFH, ESPERA_SOLTAR

ESPERA_PRESSIONAR:
    MOV A, P2
    CJNE A, #0FFH, TECLA_PRESSIONADA
    SJMP ESPERA_PRESSIONAR

TECLA_PRESSIONADA:
    CPL A
    RET

DELAY:
    MOV R6, #0FFH
DELAY_LOOP1:
    MOV R7, #0FFH
DELAY_LOOP2:
    DJNZ R7, DELAY_LOOP2
    DJNZ R6, DELAY_LOOP1
    RET

SEQUENCIA:
    DB 11111110B
    DB 10111111B
    DB 11111011B
    DB 11011111B
    DB 11101111B

END
