ORG 0000H

START:
    MOV DPTR, #SEQUENCIA
    MOV R0, #0

MOSTRA_SEQUENCIA:
    MOV A, R0
    MOVC A, @A+DPTR
    MOV P1, A
    ACALL DELAY

    INC R0
    CJNE R0, #05, MOSTRA_SEQUENCIA

    MOV P1, #0FFh

LE_TECLAS:
    ACALL LER_TECLA
    CPL A
    MOV P1, A
    SJMP LE_TECLAS

LER_TECLA:
    MOV A, P2
ESPERA_SOLTAR:
    CJNE A, #0FFh, ESPERA_SOLTAR
    MOV A, P2
ESPERA_PRESSIONAR:
    CJNE A, #0FFh, FIM_LEITURA
    MOV A, P2
    SJMP ESPERA_PRESSIONAR

FIM_LEITURA:
    MOV A, P2
    RET

DELAY:
    MOV R6, #0FFh
    MOV R7, #0FFh
ATRASO:
    DJNZ R6, ATRASO
    DJNZ R7, ATRASO
    RET

SEQUENCIA:
    DB 11111110b
    DB 10111111b
    DB 11111011b
    DB 11011111b
    DB 11101111b
